### ISSUE TITLE
Suggestion: Write warning records to MySQL database.

### ISSUE THREAD

**Issue by Firav** [shawlaf/Banmanager#7]
It would be nice if the warning records were written to the database so they could be pulled by some website API.

**Comment by Firav** [comment]
This may already be a thing, but I do not know. Im still not able to successfully perform any commands to have anything written to the table.

**Comment by shawlaf** [comment]
Please elaborate what exactly you mean by "warning records". Do you mean warnings issued to players? Because those are actually supposed to be written to the database.

**Comment by Firav** [comment]
Issue fixed in 1.1.1 -- Would it be possible to add the type of punishment within the punishments table? Like if its a warning, it will be stored as a warning, ban, etc. Also added id numbers, ie incident 1,28,128,etc.

**Comment by shawlaf** [comment]
Punishments have id's, they're stored in the `id` column and are a UUID String.
The Type is stored as an integer in the column `type`, the type ranges from 0-3:
The type integer is the ordinal of the Type in https://github.com/shawlaf/Banmanager/blob/universal/Core/src/me/shawlaf/banmanager/core/punish/PunishmentType.java
