### ISSUE TITLE
Suggestion: Allow modification of messages

### ISSUE THREAD

**Issue by Firav** [shawlaf/Banmanager#8]
Possible language file? I just feel that displaying a "moderators" IP to one who has been punished is a bit dangerous.

**Comment by shawlaf** [comment]
IPS are only shown to people with the permission `banmanager.punish.info.view_ip`. As long as this permission node is only given to trusted people, IP addresses are safe.

**Comment by Firav** [comment]
My apologies. Didn't read up on the documentation entirely well.

**Comment by Firav** [comment]
I still suggest that a language file to be added or the ability to modify messages within the config. Makes for more customization.

**Comment by Firav** [comment]
Added -- Closing

**Comment by Firav** [comment]
Quick reopen -- Any way to contact you outside of GitHub? (Steam, etc.)

**Comment by shawlaf** [comment]
You can DM me on twitter: https://twitter.com/shawlaf_ or discord: Florian#4930
